# Generated by Django 4.0.3 on 2022-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('massege', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
