# Generated by Django 4.0.3 on 2022-03-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_massege_blog_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Games',
        ),
    ]
