# Generated by Django 4.0.3 on 2022-03-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_blog_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Blog',
        ),
    ]
