# Generated by Django 4.0.3 on 2022-03-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_games_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
