# Generated by Django 4.0.3 on 2022-03-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comic_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
